export const TOOL_CATEGORIES = [
  { id: "sitemap", name: "Sitemap Tools" },
  { id: "converter", name: "Format Conversion" },
  { id: "ai-chat", name: "AI Chat" },
  { id: "ai-generator", name: "AI Generators" },
  { id: "ai-studio", name: "AI Studio & Business" },
  { id: "faq", name: "FAQ Generation" },
  { id: "utility", name: "Utility Tools" },
];

export const TOOLS = [
  { id: "sitemap-checker", name: "Sitemap Finder & Checker", desc: "Find and validate all sitemaps on a website, discover hidden sitemaps, and count URLs.", category: "sitemap" },
  { id: "sitemap-validator", name: "Sitemap Validator", desc: "Validate XML sitemaps for errors, compliance, and SEO optimization.", category: "sitemap" },
  { id: "sitemap-generator", name: "XML Sitemap Generator", desc: "Crawl a website to generate an XML sitemap with up to 50,000 URLs.", category: "sitemap" },
  { id: "sitemap-url-extractor", name: "Sitemap URL Extractor", desc: "Extract all URLs from a sitemap.xml.", category: "sitemap" },
  { id: "sitemap-urls-comparison", name: "Sitemap Comparison Tool", desc: "Compare two sitemaps and find differences.", category: "sitemap" },
  { id: "sitemap-split-merger", name: "Sitemap Split/Merge", desc: "Split a large sitemap or merge multiple sitemaps.", category: "sitemap" },
  { id: "sitemap-analytics", name: "Sitemap Analytics", desc: "Analyze sitemap structure and URL distribution.", category: "sitemap" },
  { id: "sitemap-index-generator", name: "Sitemap Index Generator", desc: "Generate a sitemap index from multiple sitemaps.", category: "sitemap" },
  { id: "sitemap-robots-generator", name: "Sitemap to Robots.txt", desc: "Generate robots.txt entries from your sitemaps.", category: "sitemap" },
  { id: "sitemap-frequency-analyzer", name: "Sitemap Frequency Analyzer", desc: "Analyze changefreq and lastmod patterns.", category: "sitemap" },
  { id: "website-url-extractor", name: "Website URL Extractor", desc: "Crawl and extract URLs from any website.", category: "sitemap" },
  { id: "robots-txt-checker", name: "Robots.txt Checker", desc: "Check robots.txt rules and crawl permissions.", category: "sitemap" },
  { id: "convert-json-to-markdown", name: "JSON to Markdown", desc: "Convert JSON data into clean Markdown.", category: "converter" },
  { id: "convert-csv-to-markdown", name: "CSV to Markdown", desc: "Convert CSV tables into Markdown tables.", category: "converter" },
  { id: "convert-html-to-markdown", name: "HTML to Markdown", desc: "Convert HTML content into Markdown.", category: "converter" },
  { id: "convert-xml-to-markdown", name: "XML to Markdown", desc: "Convert XML into readable Markdown.", category: "converter" },
  { id: "convert-rtf-to-markdown", name: "RTF to Markdown", desc: "Convert RTF documents into Markdown.", category: "converter" },
  { id: "convert-paste-to-markdown", name: "Paste to Markdown", desc: "Paste any text and convert it to Markdown.", category: "converter" },
  { id: "convert-webpage-to-markdown", name: "Webpage to Markdown", desc: "Fetch a webpage and convert it to Markdown.", category: "converter" },
  { id: "convert-notion-to-markdown", name: "Notion to Markdown", desc: "Convert Notion pages into Markdown.", category: "converter" },
  { id: "convert-google-docs-to-markdown", name: "Google Docs to Markdown", desc: "Convert Google Docs into Markdown.", category: "converter" },
  { id: "convert-pdf-to-markdown", name: "PDF to Markdown", desc: "Convert PDF documents into Markdown.", category: "converter" },
  { id: "convert-docx-to-markdown", name: "DOCX to Markdown", desc: "Convert Word documents into Markdown.", category: "converter" },
  { id: "ai-chat-with-your-text-data", name: "AI Chat: Text Data", desc: "Chat with your pasted text using AI.", category: "ai-chat" },
  { id: "ai-chat-with-your-website-data", name: "AI Chat: Website Data", desc: "Train AI on your website and chat with it.", category: "ai-chat" },
  { id: "ai-chat-with-your-document-data", name: "AI Chat: Document Data", desc: "Chat with uploaded documents using AI.", category: "ai-chat" },
  { id: "ai-chat-with-your-pdf-document-data", name: "AI Chat: PDF", desc: "Chat with PDF documents — PDF chatbot.", category: "ai-chat" },
  { id: "ai-chat-with-your-word-document-data", name: "AI Chat: Word", desc: "Chat with Word documents using AI.", category: "ai-chat" },
  { id: "ai-chatbot-conversation-analysis", name: "AI Conversation Analysis", desc: "Analyze chatbot conversations for insights.", category: "ai-chat" },
  { id: "ai-prompt-generator", name: "AI Prompt Generator", desc: "Generate high-quality AI prompts.", category: "ai-generator" },
  { id: "ai-prompt-optimizer", name: "AI Prompt Optimizer", desc: "Optimize prompts for better AI results.", category: "ai-generator" },
  { id: "ai-faq-generator", name: "AI FAQ Generator", desc: "Generate FAQs from any content with AI.", category: "ai-generator" },
  { id: "ai-reply-generator", name: "AI Reply Generator", desc: "Generate professional customer replies.", category: "ai-generator" },
  { id: "ai-answer-generator", name: "AI Answer Generator", desc: "Generate accurate answers for support questions.", category: "ai-generator" },
  { id: "ai-email-response-generator", name: "AI Email Response Generator", desc: "Draft polished email responses with AI.", category: "ai-generator" },
  { id: "ai-letter-generator", name: "AI Letter Generator", desc: "Generate formal and informal letters.", category: "ai-generator" },
  { id: "ai-blog-title-generator", name: "AI Blog Title Generator", desc: "Generate click-worthy blog titles.", category: "ai-generator" },
  { id: "ai-chatbot-name-generator", name: "AI Chatbot Name Generator", desc: "Generate brandable chatbot names.", category: "ai-generator" },
  { id: "ai-saas-brand-name-generator", name: "AI SaaS Brand Name Generator", desc: "Generate SaaS brand name ideas.", category: "ai-generator" },
  { id: "customer-service-script-generator", name: "Customer Service Script Generator", desc: "Create support scripts for common scenarios.", category: "ai-generator" },
  { id: "ai-search-visibility-checker", name: "AI Search Visibility Checker", desc: "Check how AI search engines see your content.", category: "ai-studio" },
  { id: "ai-qa-content-generator", name: "AI Q&A Content Generator", desc: "Generate Q&A content for SEO and support.", category: "ai-studio" },
  { id: "vlog-title-description-generator", name: "Vlog Title & Description Generator", desc: "Generate vlog titles and descriptions.", category: "ai-studio" },
  { id: "video-chapter-timestamp-generator", name: "Video Chapter/Timestamp Generator", desc: "Generate video chapters and timestamps.", category: "ai-studio" },
  { id: "broll-script-generator", name: "B-Roll Creative Script Generator", desc: "Generate B-roll shot lists and scripts.", category: "ai-studio" },
  { id: "customer-service-qa-analyzer", name: "Customer Service QA Analyzer", desc: "Analyze support QA quality and sentiment.", category: "ai-studio" },
  { id: "prd-generator", name: "PRD Generator", desc: "Generate product requirements documents.", category: "ai-studio" },
  { id: "internal-email-tone-adjuster", name: "Internal Email Tone Adjuster", desc: "Rewrite emails with the right tone.", category: "ai-studio" },
  { id: "ai-subscription-pricing-advisor", name: "AI Subscription Pricing Advisor", desc: "Get AI advice on SaaS pricing plans.", category: "ai-studio" },
  { id: "saas-cost-calculator", name: "SaaS Cost Calculator", desc: "Calculate SaaS infrastructure and margin costs.", category: "ai-studio" },
  { id: "vc-term-sheet-simulator", name: "VC Term Sheet Simulator", desc: "Simulate VC term sheet scenarios.", category: "ai-studio" },
  { id: "website-faq-generator", name: "Website FAQ Generator", desc: "Generate FAQs from multiple website URLs.", category: "faq" },
  { id: "webpage-to-faq-generator", name: "Webpage FAQ Generator", desc: "Turn a single webpage into FAQs.", category: "faq" },
  { id: "pdf-to-faq-generator", name: "PDF FAQ Generator", desc: "Generate FAQs from PDF documents.", category: "faq" },
  { id: "docx-to-faq-generator", name: "DOCX FAQ Generator", desc: "Generate FAQs from Word documents.", category: "faq" },
  { id: "html-to-faq-generator", name: "HTML FAQ Generator", desc: "Generate FAQs from HTML content.", category: "faq" },
  { id: "google-docs-to-faq-generator", name: "Google Docs FAQ Generator", desc: "Generate FAQs from Google Docs.", category: "faq" },
  { id: "notion-to-faq-generator", name: "Notion FAQ Generator", desc: "Generate FAQs from Notion pages.", category: "faq" },
  { id: "chatbot-roi-calculator", name: "Chatbot ROI Calculator", desc: "Estimate savings from AI customer support.", category: "utility" },
  { id: "email-signature-generator", name: "Email Signature Generator", desc: "Generate professional email signatures.", category: "utility" },
];
